#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# apt-get
###############################################################################

if [[ -f $DIR/packages/apt ]]; then
  exec<$DIR/packages/apt
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      packages="$packages $line"
    fi
  done
  sudo apt-get install -y $packages
fi

###############################################################################
# linuxbrew
###############################################################################

if ! type "brew" > /dev/null; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
fi

if [[ -f $DIR/packages/linuxbrew ]]; then
  exec<$DIR/packages/linuxbrew
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      packages="$packages $line"
    fi
  done
  brew install $packages
fi

echo "Finished Linuxbrew Package Install"

/bin/bash /home/linuxbrew/.linuxbrew/opt/fzf/install --all
